apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcpserver
  namespace: mcpserver
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcpserver
                port:
                  number: 80
