apiVersion: v1
kind: Service
metadata:
  name: mcpserver
  namespace: mcpserver
spec:
  type: ClusterIP
  selector:
    app: mcpserver
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
